---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: <BRANCH>
  labels:
    app: odoo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8069
  selector:
    app: odoo
    tier: backend
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo
  namespace: <BRANCH>
  labels:
    app: odoo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: odoo
        tier: backend
    spec:
      containers:
        - image: gcr.io/<PROJECT>/odoo:<BRANCH>-<SHA>
          name: odoo
          env:
          - name: HOST
            value: db
          - name: USER
            value: odoo
          - name: PASSWORD
            value: odoo
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
#          readinessProbe:
#            httpGet:
#              path: /web/database/selector
#              port: 8069
          volumeMounts:
            - name: <BRANCH>-filestore-nfs
              mountPath: /var/lib/odoo/.local/share/Odoo/filestore/
            - name: <BRANCH>-venv-nfs
              mountPath: /opt/venv
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "chown -R odoo. /var/log/odoo"]
          resources:
            requests:
              memory: "1Gi"
              cpu: "400m"
            limits:
              memory: "2Gi"
              cpu: "800m"
      volumes:
      - name: <BRANCH>-filestore-nfs
        persistentVolumeClaim:
          claimName: <BRANCH>-filestore-nfs
      - name: <BRANCH>-venv-nfs
        persistentVolumeClaim:
          claimName: <BRANCH>-venv-nfs