---
kind: Service
apiVersion: v1
metadata:
  name: file
  namespace: konek
spec:
  ports:
    - name: file
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: file
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: file
  namespace: konek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
      - name: file
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: file
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: file-disk
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
      volumes:
        - name: file-disk
          gcePersistentDisk:
            pdName: vieterp-vn-file
            fsType: ext4