---
kind: Service
apiVersion: v1
metadata:
  name: nfs
  namespace: konek
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs
  namespace: konek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
      - name: nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-disk
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "100m"
      volumes:
        - name: nfs-disk
          gcePersistentDisk:
            pdName: konek-vn-uat
            fsType: ext4