---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: <BRANCH>
  labels:
    app: db
spec:
  ports:
    - port: 5432
  selector:
    app: db
    tier: backend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: <BRANCH>
  labels:
    app: db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
        tier: backend
    spec:
      containers:
      - image: postgres:10.0-alpine
        name: db
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: <BRANCH>-db-pvc
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "900Mi"
            cpu: "250m"
          limits:
            memory: "1200Mi"
            cpu: "350m"
      volumes:
      - name: <BRANCH>-db-pvc
        persistentVolumeClaim:
          claimName: <BRANCH>-db-pvc