steps:
- name: 'ubuntu'
  args: ['bash', './build-test.sh']
  env:
  - 'BRANCH=$BRANCH_NAME'
  - 'PROJECT=$PROJECT_ID'
  - 'SHA=$SHORT_SHA'
  id: 'bash'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME'
  - '--tag=gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME-$SHORT_SHA'
  - '--file=config/docker/vieterp/Dockerfile'
  - '.'
  wait_for: ['bash']
  id: 'docker-odoo'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME-worker'
  - '--tag=gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME-$SHORT_SHA-worker'
  - './worker/$BRANCH_NAME'
  wait_for: ['docker-odoo']
  id: 'docker-worker'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME-$SHORT_SHA'
  wait_for: ['docker-odoo']
  id: 'push-odoo'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME-$SHORT_SHA-worker'
  wait_for: ['docker-worker']
  id: 'push-worker'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - './config/$BRANCH_NAME/vieterp-test.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=konek-vn'
  wait_for: ['push-worker']

images:
- 'gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME'
- 'gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME-worker'
- 'gcr.io/$PROJECT_ID/odoo:$BRANCH_NAME-$SHORT_SHA-worker'