---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vieterp
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
    tier: backend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: vieterp
  labels:
    app: redis
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - image: redis:5-alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis