---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vieterp
  labels:
    app: db
spec:
  ports:
    - port: 5432
  selector:
    app: db
    tier: backend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: vieterp
  labels:
    app: db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
        tier: backend
    spec:
      containers:
      - image: postgres:10.0
        name: db
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: db-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-pvc
        persistentVolumeClaim:
          claimName: db-pvc