---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: vieterp
  labels:
    app: odoo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8069
  selector:
    app: odoo
    tier: backend
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo
  namespace: vieterp
  labels:
    app: odoo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: odoo
        tier: backend
    spec:
      containers:
        - image: vieterp/odoo:<VERSION>
          name: odoo
          env:
          - name: HOST
            value: db
          - name: USER
            value: odoo
          - name: PASSWORD
            value: odoo
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
#          readinessProbe:
#            httpGet:
#              path: /web/database/selector
#              port: 8069
          volumeMounts:
          - name: vieterp-nfs
            mountPath: /var/lib/odoo
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "chown -R odoo. /var/lib/odoo && chown -R odoo. /var/log/odoo"]
      imagePullSecrets:
        - name: vieterp-docker
      volumes:
      - name: vieterp-nfs
        persistentVolumeClaim:
          claimName: vieterp-nfs