---
kind: Namespace
apiVersion: v1
metadata:
  name: vieterp
  labels:
    name: vieterp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vieterp-gitlab
  namespace: vieterp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vieterp-gitlab-vieterp
  namespace: vieterp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: vieterp-gitlab
    namespace: vieterp
---
apiVersion: v1
kind: Secret
metadata:
  name: vieterp-docker
  namespace: vieterp
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJ2aWV0ZXJwIiwicGFzc3dvcmQiOiJ2aWV0ZXJwQDIwMTciLCJlbWFpbCI6InNhbmdAdmlldGVycC5uZXQiLCJhdXRoIjoiZG1sbGRHVnljRHAyYVdWMFpYSndRREl3TVRjPSJ9fX0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: gcs-keys
  namespace: vieterp
data:
  gcs.json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidmlldGVycC1uZXQiLAogICJwcml2YXRlX2tleV9pZCI6ICIzZjI3ZWZjOWM5NWI3NmVjMmQ5YjA2ZDI5YTM0MjA5NjU5NjllZjVjIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdndJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLa3dnZ1NsQWdFQUFvSUJBUURXaEczazQwZ3BkaTVWXG5WQ2lveGpIbkErNHhPN1ZhRHNsVnJ6OFppY2RWWklMaUlhajBLUGJ3OW5kb1laUlFXMVNyMHQ1dGdIbndOWW9yXG5xNENwTk4wclRWOFZCMWt4cVk0TEZFc2dYcVBWMTMwN1BqVzU5NlFPS3FMVlhRd3dSdzhTOFVFK2ZDTlAzbDJCXG5zVnFLRGZ1cjdwaW9OV2I2TjVSOC8zbDBMMVNPYnN3aFhBVmpqNklhV2hMTmV6MWVKN3FIQ2ZsVWZPdGJ2bVhUXG52dWFoaXRnY0tZRUx5b1lUUFNpY0ZVSm1tb0xKanNJQ056Zm9sZ0h4dUZWQkpWRmNSYlZaRk5kYXpVdlg0RjM0XG4waVUxSGNWTVZzYytUQ2N4L2F6OUpzWU0vTGp6K3RidDYxL2hTVVFWSENsNmZjaGN5aXdlNUFXZk1BN1l1bndLXG5CVVBmbVdXM0FnTUJBQUVDZ2dFQVUzamRnRUsyZWplNzZNVWlPeVpBRmNvUVBnVWpXTU5ITWJuSy9tZC84cWoxXG5Td1BaQ0FVR3JoWGh1Zks2Y1JoUTFybHJoc1dHN1dNUC9GVTBiK01icXJWbEtid2R4M2JZU0ZSaHRWdE9PakFyXG5VVW13UTBockJINHZ0WUdLOUNBNmE5OEh5Y1lwUVhOZ0JFN2NVYnNHTXMxWmhwNmREd0Znbk5FV1ZCRDB3S1VDXG50dW5qV0pWUDJOVGZGL0tyYVF6b0ZZYTYxS3BBYjZ1TzJ3SytTNitmNy93RFozSVZUYlB0NTdESm0yOEpRNEovXG5VQVFaTFJYVEVPVGJYeHRHVWtUTVoxb3htT1prN0grZ0w4NVN3Nmt2aFgrZTFjWjNnbzZVdjVNTDRwb0NscVY0XG45RStjTmd2ajR6WEN3ei9yeHdmL0QxNmd3QUF4clUzRU1NMFhBWitXL1FLQmdRRDV6eG01Nm5rSXJFV2lGNndqXG5mU05BbUFINFlQU01KUjFqYnlPWkljUjRXK3F1d3lkVGZoZG1jeDBZRW9ZeUJpRStzcVhKQXN3dFFrcEg1dnQ5XG5LRVJvMGFrWVFjaG95ajQycVBHS0pyQXpPUnlXM0xDMGloR1FhTmhvUDBFU1dPOS9vZmtIU0F5QkZIcWhrN3doXG54TTY0WGxkZ2ZKQTB1amhlTFhjcEZzTnU1UUtCZ1FEYjFXd3dPOFZST2NxZDhqQk5MeVppcTN6OWdsVFJTd21iXG5Sb283NXZGUmFpb29kS2w1YUVIbjJVNVM2WkZ2VnpCUEtQY29YVWg5MitnanBmcUlYR09ta0Z2N045WjNEdzJxXG5WanRScTAxVyt4dXJFSG9mTGZVRjJ2Y05CWGFuUnRNYnoxaTYxSGxwSnBjdWFyOWFCUCs3a3locHg5U2t0Q082XG5nT29wSnhVY2F3S0JnUUNZenVla3cxb2dSUWtmV3kyd1U4YnhwMHBsUGlHNWJLYXFnWHljR256TlJ5U3FuTFA4XG5yYi93cW0vY250QTUzMmdNcTBrZ1NiYk41S1A5a2J5NjFadnJKbjB5V21NV1BzaUp0UlJ6ZHJFSDFHSzVvZXZ4XG50QmVFWjY0aExyaEdXZUsvQnp5SENMcWxadnFReGdjcC9QS2E4eEt0OGVSZ2JKMDRkc1ZTZkJzMlJRS0JnUURBXG5vVVE3QTdVRVZ1S3dBbS9Hd29FZFJ1Mndhb3NPRm5XbGhXdE4wREUzU1JNRi9pd2ZBWGQyeE5rNEdBamppbi8vXG5iWU1kOEplOENYMWg5MmdRSXYwREVFNDVWUlZ0b0ZnMklYZTdPYUw4aSs4VHQ4MTdFdGM0dVVWd09KQmZSZFZvXG44Z2pyTlpIcHpQSCtyM1ZiV1RRSjFvbzhIdW03SlVxRmU3ODBMbFgyWHdLQmdRQ0JDMTRVVTJLOVRPeFl5bGJjXG5LSFpJbTN5T3BZZ1hObm40NGR0a2ZmZC95ZzI0WUJhRXUrc3Q5bUpTcnhQZnhUaXNYNUhOeFdic3J0ZFdlaHFCXG5Ub2prT2J0R3dHMHNXNW1nMGh5V01pMTNQcTl0TWpRaVdzQzJBNUgzYTl2Q3k1N1NFbGkxcUlhbEtBVWlUcE13XG5EMGtmaHFTSmhVamZMUnFPRmJXZVZ4aWZKZz09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZ2NzLTIxNEB2aWV0ZXJwLW5ldC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTAzMDAwNjAzMDQ3NTEzNzY1NTQiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2djcy0yMTQlNDB2aWV0ZXJwLW5ldC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=
