---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: vieterp
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    tier: backend
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thethaosi-mysql-pvc
  namespace: vieterp
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: vieterp
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - image: mysql:5.6
        name: mysql56
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: thethaosi-mysql-pvc
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "600Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "200m"
      volumes:
      - name: thethaosi-mysql-pvc
        persistentVolumeClaim:
          claimName: thethaosi-mysql-pvc