---
kind: Service
apiVersion: v1
metadata:
  name: queue
  namespace: <BRANCH>
spec:
  ports:
    - name: queue
      port: 4730
  selector:
    app: queue
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue
  namespace: <BRANCH>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: gcr.io/<PROJECT>/gearmand:1.1.18
        ports:
          - name: queue
            containerPort: 4730
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"