---
apiVersion: v1
kind: Service
metadata:
  name: mail
  namespace: thethaosi
  labels:
    app: mail
spec:
  ports:
  - port: 1025
    name: smtp
    protocol: TCP
    targetPort: 1025
  - port: 1080
    name: web
    protocol: TCP
    targetPort: 1080
  selector:
    app: mail
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mail
  namespace: thethaosi
  labels:
    app: mail
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mail
        tier: frontend
    spec:
      containers:
      - image: gcr.io/vieterp-vn/mail:1.4
        name: redis
        env:
        - name: SENDGRID_API_KEY
          value: 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
        ports:
        - containerPort: 1025
          name: smtp
        - containerPort: 1080
          name: web
        resources:
          requests:
            memory: "20Mi"
            cpu: "50m"
          limits:
            memory: "40Mi"
            cpu: "100m"